apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expense-tracker
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "<YOUR_ROOT_PASSWORD>"
  MYSQL_PASSWORD: "<YOUR_MYSQL_PASSWORD>"
